# Generated by Django 2.2 on 2019-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190402_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timeTask',
            field=models.TimeField(),
        ),
    ]
