# Generated by Django 2.2 on 2019-04-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190402_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='timeTask',
            new_name='timeTaskl',
        ),
    ]
