# Generated by Django 2.2 on 2019-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190402_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timeTaskl',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
