# Generated by Django 2.2 on 2019-04-03 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190403_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dateEvent',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
