# Generated by Django 2.2 on 2019-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_dateevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateEvent',
            field=models.DateField(default='2019-04-03'),
        ),
    ]
